USE [master]
GO

/****** Object:  Database [Grupo A]    Script Date: 02/04/2022 11:24:53 ******/
CREATE DATABASE [Grupo A]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Grupo A', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Grupo A.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Grupo A_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Grupo A_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Grupo A].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Grupo A] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Grupo A] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Grupo A] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Grupo A] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Grupo A] SET ARITHABORT OFF 
GO

ALTER DATABASE [Grupo A] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Grupo A] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Grupo A] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Grupo A] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Grupo A] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Grupo A] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Grupo A] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Grupo A] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Grupo A] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Grupo A] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Grupo A] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Grupo A] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Grupo A] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Grupo A] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Grupo A] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Grupo A] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Grupo A] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Grupo A] SET RECOVERY FULL 
GO

ALTER DATABASE [Grupo A] SET  MULTI_USER 
GO

ALTER DATABASE [Grupo A] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Grupo A] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Grupo A] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Grupo A] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Grupo A] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Grupo A] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Grupo A] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Grupo A] SET  READ_WRITE 
GO

